const journal_list = {
  links: {
    next: "https://api.himexp.ru/v1/project/journal/?categories=&limit=20&ordering=&page=2&projects=&search=",
    previous: null,
    count: 4,
  },
  total_objects_count: 67,
  current_data_count: 20,
  results: [
    {
      project: null,
      order: 173,
      material: "Нефтепродукты",
      producer: null,
      analysis: "Определение температуры вспышки в закрытом тигле (светлые нефтепродукты)",
      parameter: "температура вспышки в закрытом тигле",
      parameter_value: "35,9",
    },
    {
      project: null,
      order: 174,
      material: "Нефтепродукты",
      producer: null,
      analysis: "Определение температуры вспышки в закрытом тигле (светлые нефтепродукты)",
      parameter: "температура вспышки в закрытом тигле",
      parameter_value: "56,0",
    },
    {
      project: null,
      order: 176,
      material: "Нефтепродукты",
      producer: "ООО \"31\"",
      analysis: "Определение температуры вспышки в закрытом тигле (светлые нефтепродукты)",
      parameter: "температура вспышки в закрытом тигле",
      parameter_value: "10",
    },
    {
      project: null,
      order: 166,
      material: "Нефтепродукты",
      producer: "ООО \"ОДУВАНЧИК\"",
      analysis: "Определение температуры вспышки в закрытом тигле (светлые нефтепродукты)",
      parameter: "температура вспышки в закрытом тигле",
      parameter_value: "63,0",
    },
    {
      project: null,
      order: 167,
      material: "Нефтепродукты",
      producer: "ООО \"ОДУВАНЧИК\"",
      analysis: "Определение температуры вспышки в закрытом тигле (светлые нефтепродукты)",
      parameter: "температура вспышки в закрытом тигле",
      parameter_value: "452",
    },
    {
      project: null,
      order: 165,
      material: "Нефтепродукты",
      producer: "ООО \"ОДУВАНЧИК\"",
      analysis: "Определение температуры вспышки в закрытом тигле (светлые нефтепродукты)",
      parameter: "температура вспышки в закрытом тигле",
      parameter_value: "24",
    },
    {
      project: null,
      order: 176,
      material: "Нефтепродукты",
      producer: "ООО \"31\"",
      analysis: "Определение плотности тёмных нефтепродуктов",
      parameter: "плотность",
      parameter_value: "120",
    },
    {
      project: null,
      order: 168,
      material: "Нефтепродукты",
      producer: "ООО \"НЕФТЕХИМ-ЭКСПЕРТ\"",
      analysis: "Определение плотности тёмных нефтепродуктов",
      parameter: "плотность",
      parameter_value: "452",
    },
    {
      project: null,
      order: 178,
      material: "Бензин",
      producer: null,
      analysis: "Определение плотности светлых нефтепродуктов",
      parameter: "плотность при 15°c",
      parameter_value: "34",
    },
    {
      project: null,
      order: 178,
      material: "Бензин",
      producer: null,
      analysis: "Определение углеводородного состава нефтепродуктов методом капиллярной газовой хроматографии",
      parameter: "углеводородный состав",
      parameter_value: "34",
    },
    {
      project: null,
      order: 161,
      material: "Нефтепродукты",
      producer: "0",
      analysis: "Определение содержания основного вещества",
      parameter: "содержание основного в-ва",
      parameter_value: "10",
    },
    {
      project: null,
      order: 171,
      material: "Нефтепродукты",
      producer: null,
      analysis: "Определение содержания основного вещества",
      parameter: "содержание основного в-ва",
      parameter_value: "95,9",
    },
    {
      project: null,
      order: 178,
      material: "Бензин",
      producer: null,
      analysis: "Определение содержания основного вещества",
      parameter: "содержание основного в-ва",
      parameter_value: "88",
    },
    {
      project: null,
      order: 155,
      material: "Нефтепродукты",
      producer: "0",
      analysis: "Определение содержания основного вещества",
      parameter: "содержание основного в-ва",
      parameter_value: "89,07",
    },
    {
      project: null,
      order: 149,
      material: "Бензин",
      producer: "0",
      analysis: "Определение концентрации свинца, железа, марганца",
      parameter: "содержание свинца",
      parameter_value: "НПКО",
    },
    {
      project: null,
      order: 150,
      material: "Нефтепродукты",
      producer: "0",
      analysis: "Определение концентрации свинца, железа, марганца",
      parameter: "содержание марганца,",
      parameter_value: "НПКО",
    },
    {
      project: null,
      order: 149,
      material: "Бензин",
      producer: "0",
      analysis: "Определение концентрации свинца, железа, марганца",
      parameter: "содержание марганца,",
      parameter_value: "НПКО",
    },
    {
      project: null,
      order: 150,
      material: "Нефтепродукты",
      producer: "0",
      analysis: "Определение концентрации свинца, железа, марганца",
      parameter: "содержание железа,",
      parameter_value: "18,8",
    },
    {
      project: null,
      order: 149,
      material: "Бензин",
      producer: "0",
      analysis: "Определение концентрации свинца, железа, марганца",
      parameter: "содержание железа,",
      parameter_value: "18,8",
    },
    {
      project: null,
      order: 150,
      material: "Нефтепродукты",
      producer: "0",
      analysis: "Определение концентрации свинца, железа, марганца",
      parameter: "содержание свинца",
      parameter_value: "НПКО",
    },
  ],
};

export const journal = (req, res) => {
  res.status(200).json(journal_list);
};
