const orders_list = {
  links: { next: null, previous: null, count: 1 },
  total_objects_count: 7,
  current_data_count: 7,
  results: [
    {
      id: 5,
      profile: {
        id: 5,
        user: 4,
        company: 18,
        fio: "Гайдуков Павел Клиент",
        company__short_title: "ООО \"ГРУППА 789\"",
        company__is_active: true,
        company__date_created: "2021-11-24T06:23:37Z",
        date_created: "2022-02-03T09:40:21.578103+07:00",
        user__is_blocked: false,
      },
      price: "1500.00",
      status: 15,
      is_paid: false,
      date_created: "2022-02-11T16:30:44.761972+07:00",
    },
    {
      id: 7,
      profile: {
        id: 5,
        user: 4,
        company: 18,
        fio: "Гайдуков Павел Клиент",
        company__short_title: "ООО \"ГРУППА 789\"",
        company__is_active: true,
        company__date_created: "2021-11-24T06:23:37Z",
        date_created: "2022-02-03T09:40:21.578103+07:00",
        user__is_blocked: false,
      },
      price: "1600.00",
      status: 20,
      is_paid: false,
      date_created: "2022-03-16T10:43:02.747157+07:00",
    },
    {
      id: 3,
      profile: {
        id: 5,
        user: 4,
        company: 18,
        fio: "Гайдуков Павел Клиент",
        company__short_title: "ООО \"ГРУППА 789\"",
        company__is_active: true,
        company__date_created: "2021-11-24T06:23:37Z",
        date_created: "2022-02-03T09:40:21.578103+07:00",
        user__is_blocked: false,
      },
      price: "1000.00",
      status: 30,
      is_paid: true,
      date_created: "2022-02-03T13:06:07.252214+07:00",
    },
    {
      id: 4,
      profile: {
        id: 5,
        user: 4,
        company: 18,
        fio: "Гайдуков Павел Клиент",
        company__short_title: "ООО \"ГРУППА 789\"",
        company__is_active: true,
        company__date_created: "2021-11-24T06:23:37Z",
        date_created: "2022-02-03T09:40:21.578103+07:00",
        user__is_blocked: false,
      },
      price: "2500.00",
      status: 90,
      is_paid: true,
      date_created: "2022-02-04T10:08:37.840344+07:00",
    },
    {
      id: 2,
      profile: {
        id: 5,
        user: 4,
        company: 18,
        fio: "Гайдуков Павел Клиент",
        company__short_title: "ООО \"ГРУППА 789\"",
        company__is_active: true,
        company__date_created: "2021-11-24T06:23:37Z",
        date_created: "2022-02-03T09:40:21.578103+07:00",
        user__is_blocked: false,
      },
      price: "1000.00",
      status: 90,
      is_paid: true,
      date_created: "2022-02-03T13:02:34.587016+07:00",
    },
    {
      id: 1,
      profile: {
        id: 5,
        user: 4,
        company: 18,
        fio: "Гайдуков Павел Клиент",
        company__short_title: "ООО \"ГРУППА 789\"",
        company__is_active: true,
        company__date_created: "2021-11-24T06:23:37Z",
        date_created: "2022-02-03T09:40:21.578103+07:00",
        user__is_blocked: false,
      },
      price: "1000.00",
      status: 30,
      is_paid: true,
      date_created: "2022-02-03T12:54:40.029034+07:00",
    },
    {
      id: 6,
      profile: {
        id: 5,
        user: 4,
        company: 18,
        fio: "Гайдуков Павел Клиент",
        company__short_title: "ООО \"ГРУППА 789\"",
        company__is_active: true,
        company__date_created: "2021-11-24T06:23:37Z",
        date_created: "2022-02-03T09:40:21.578103+07:00",
        user__is_blocked: false,
      },
      price: "1500.00",
      status: 15,
      is_paid: true,
      date_created: "2022-02-15T13:55:42.936751+07:00",
    },
  ],
};

const orderData = {
  id: 178,
  target: "Согласно НД",
  profile: {
    id: 26,
    user: {
      id: 8,
      fio: "Гайдуков Павел клиент",
      email: "test4@gokengu.ru",
      phone: "79236418341",
      date_joined: "2022-07-15T11:26:34+07:00",
      is_blocked: false,
    },
    company: {
      id: 18,
      short_title: "ООО \"СК7683\"",
      inn: "9718166111",
      is_active: true,
      contact_fio: "Гайдуков Павел клиент",
      email: "test4@gokengu.ru",
      phone: "79236418341",
      date_created: "2022-07-18T15:59:18.009107+07:00",
    },
    date_created: "2022-07-18T15:59:18.013946+07:00",
  },
  price: "18950.00",
  status: 80,
  is_paid: true,
  date_created: "2022-07-07T10:11:36.313067+07:00",
  date_updated: "2022-07-08T09:46:32.680690+07:00",
  description: "",
  product: {
    id: 111,
    number_probe: null,
    date_probe: "2022-07-27",
    date_created: "2022-07-27",
    description: "Прозрачная жидкость светло-жёлтого цвета с резким химическим запахом.",
    quantity: "15.00",
    category: 4,
    producer: null,
    documents: [
      {
        id: 26,
        title: "Акт отбора пробы",
        // eslint-disable-next-line max-len
        document:
          // eslint-disable-next-line max-len
          "http://192.168.31.198:8000/media/products/2263/documents/%D0%90%D0%BA%D1%82_%D0%BE%D1%82%D0%B1%D0%BE%D1%80%D0%B0_%D0%BF%D1%80%D0%BE%D0%B1%D1%8B_nxNWECz",
      },
      {
        id: 27,
        title: "УПД к заказу  № 129.pdf",
        // eslint-disable-next-line max-len
        document:
          "http://192.168.31.198:8000/media/products/2263/documents/%D0%A3%D0%9F%D0%94_%D0%BA_%D0%B7%D0%B0%D0%BA%D0%B0%D0%B7%D1%83___129.pdf",
      },
    ],
    rest: 7,
    status: 20,
    sticker: "https://predlab.s3.amazonaws.com/media/private/order/178/sticker.pdf",
  },
  technical_task: "Тут, наверное, нужно указать пожелания. Проводите исследование не торопясь.",
  technical_file: "https://predlab.s3.amazonaws.com/media/private/order/178/test-report.pdf",
  need_test_report_paper: false,
  quickly: false,
  tara_for_product_address: null,
  pickup_product_address: null,
  self_arrival: true,
  result: [
    {
      id: 265,
      order: 178,
      analysis: {
        id: 30,
        title: "Определение содержания основного вещества",
        indicator: "Содержание основного вещества",
        description: "",
        price: "3500.00",
        capacity: 300,
        sub_analyses: [
          {
            id: 141,
            title: "содержание основного в-ва",
            description: "-",
            norm: "-",
            unit: { id: 17, title: "процент", short_title: "%" },
          },
        ],
        target: 0,
        devices: [
          {
            id: 3,
            title:
              "Комплекс аппаратно-программный для медицинских исследований на базе хроматографа \"Хроматэк-Кристалл 5000.2\", № 560005",
            number: "560005",
            last_service_date: "2021-08-24",
            next_service_date: "2021-08-25",
          },
        ],
        date_interval: 5,
        method: {
          id: 27,
          title:
            "Определение индивидуального и группового углеводородного состава методом капиллярной газовой хроматографии",
          registration_number: "ГОСТ 32507",
          link: "https://docs.cntd.ru/document/1200108178",
        },
        example_unit: { id: 21, title: "килопаскаль", short_title: "кПа" },
      },
      date_created: "2022-07-07T10:11:36.326274+07:00",
      date_updated: "2022-07-08T09:03:58.308145+07:00",
      sub_results: [
        {
          id: 171,
          parent_result: 265,
          sub_analysis: {
            id: 141,
            title: "содержание основного в-ва",
            description: "-",
            norm: "-",
            unit: { id: 17, title: "процент", short_title: "%" },
          },
          value: "88",
          date_result: "2022-07-08T09:03:54.493398+07:00",
          date_created: "2022-07-08T08:52:23.372128+07:00",
          variation: "5",
        },
      ],
      executor: null,
      status: 0,
    },
    {
      id: 264,
      order: 178,
      analysis: {
        id: 13,
        title: "Определение детонационной стойкости бензинов исследовательским методом",
        indicator: "Октановое число",
        description: "",
        price: "2400.00",
        capacity: 1,
        sub_analyses: [
          {
            id: 12,
            title: "Октановое число",
            description: "не менее",
            norm: "80,0",
            unit: { id: 15, title: "Условная единица", short_title: "ед." },
          },
          {
            id: 76,
            title: "октановое число",
            description: "не менее",
            norm: "92,0",
            unit: { id: 15, title: "Условная единица", short_title: "ед." },
          },
          {
            id: 77,
            title: "октановое число",
            description: "не менее",
            norm: "95,0",
            unit: { id: 15, title: "Условная единица", short_title: "ед." },
          },
          {
            id: 78,
            title: "октановое число",
            description: "не менее",
            norm: "98,0",
            unit: { id: 15, title: "Условная единица", short_title: "ед." },
          },
        ],
        target: 0,
        devices: [
          {
            id: 7,
            title: "Установка УИТ-85",
            number: "789",
            last_service_date: "2021-08-24",
            next_service_date: "2021-08-29",
          },
        ],
        categories: [
          {
            id: 1,
            title: "Нефтепродукты",
            code: "nefteproduktyi",
            my_path: "Нефтепродукты",
            parent: null,
            description: null,
          },
          {
            id: 2,
            title: "Бензин",
            code: "benzin",
            my_path: "Нефтепродукты-->Бензин",
            parent: 1,
            description: null,
          },
          {
            id: 14,
            title: "АИ-95",
            code: "ai-95",
            my_path: "Нефтепродукты-->Бензин-->АИ-95",
            parent: 2,
            description: "",
          },
          {
            id: 24,
            title: "АИ-98",
            code: "ai-98",
            my_path: "Нефтепродукты-->Бензин-->АИ-98",
            parent: 2,
            description: null,
          },
          {
            id: 34,
            title: "аи-100",
            code: "ai-100",
            my_path: "Нефтепродукты-->Бензин-->аи-100",
            parent: 2,
            description: "",
          },
          {
            id: 46,
            title: "аи-80",
            code: "ai-80",
            my_path: "Нефтепродукты-->Бензин-->аи-80",
            parent: 2,
            description: null,
          },
          {
            id: 56,
            title: "другое (указать продукт в описании к заказу)",
            code: "drugoe-ukazat-produkt-v-opisanii-k-zakazu",
            my_path: "Нефтепродукты-->Бензин-->другое (указать продукт в описании к заказу)",
            parent: 2,
            description: "",
          },
          {
            id: 57,
            title: "аи-92",
            code: "ai-92-2",
            my_path: "Нефтепродукты-->Бензин-->аи-92",
            parent: 2,
            description: null,
          },
        ],
        date_interval: 12,
        method: {
          id: 14,
          title: "Исследовательский метод определения октанового числа",
          registration_number: "ГОСТ 8226",
          link: "https://docs.cntd.ru/document/1200128311",
        },
        example_unit: { id: 21, title: "килопаскаль", short_title: "кПа" },
      },
      date_created: "2022-07-07T10:11:36.326218+07:00",
      date_updated: "2022-07-08T09:29:18.476903+07:00",
      sub_results: [
        {
          id: 175,
          parent_result: 264,
          sub_analysis: {
            id: 78,
            title: "октановое число",
            description: "не менее",
            norm: "98,0",
            unit: { id: 15, title: "Условная единица", short_title: "ед." },
          },
          value: "34",
          date_result: "2022-07-08T09:28:15.795999+07:00",
          date_created: "2022-07-08T09:28:15.795549+07:00",
          variation: "3",
        },
        {
          id: 174,
          parent_result: 264,
          sub_analysis: {
            id: 76,
            title: "октановое число",
            description: "не менее",
            norm: "92,0",
            unit: { id: 15, title: "Условная единица", short_title: "ед." },
          },
          value: "34",
          date_result: "2022-07-08T09:28:15.738247+07:00",
          date_created: "2022-07-08T09:28:15.737681+07:00",
          variation: "3",
        },
        {
          id: 173,
          parent_result: 264,
          sub_analysis: {
            id: 77,
            title: "октановое число",
            description: "не менее",
            norm: "95,0",
            unit: { id: 15, title: "Условная единица", short_title: "ед." },
          },
          value: "34",
          date_result: "2022-07-08T09:28:15.736921+07:00",
          date_created: "2022-07-08T09:28:15.735235+07:00",
          variation: "3",
        },
        {
          id: 172,
          parent_result: 264,
          sub_analysis: {
            id: 12,
            title: "Октановое число",
            description: "не менее",
            norm: "80,0",
            unit: { id: 15, title: "Условная единица", short_title: "ед." },
          },
          value: "34",
          date_result: "2022-07-08T09:28:15.724460+07:00",
          date_created: "2022-07-08T09:28:15.723930+07:00",
          variation: "3",
        },
      ],
      executor: {
        id: 95,
        first_name: "Дмитрий",
        last_name: "Коханенко",
        patronymic: "Васильевич",
        email: "koh@ooo31.com",
        phone: "79132136810",
        is_active: true,
        is_fully_confirmed: true,
        role: 10,
        date_joined: "2021-12-20T14:18:33+07:00",
        is_staff: true,
        is_project_manager: false,
        is_blocked: false,
      },
      status: 40,
    },
    {
      id: 263,
      order: 178,
      analysis: {
        id: 37,
        title: "Определение плотности светлых нефтепродуктов",
        indicator: "Плотность",
        description: "",
        price: "250.00",
        capacity: 300,
        sub_analyses: [
          {
            id: 149,
            title: "плотность при 15°c",
            description: "",
            norm: "-",
            unit: { id: 13, title: "градус Цельсия", short_title: "˚C" },
          },
        ],
        target: 0,
        devices: [
          {
            id: 19,
            title: "Измеритель плотности жидкости вибрационный ВИП-2МР",
            number: "856084",
            last_service_date: "2021-04-15",
            next_service_date: "2022-04-14",
          },
        ],
        categories: [
          {
            id: 1,
            title: "Нефтепродукты",
            code: "nefteproduktyi",
            my_path: "Нефтепродукты",
            parent: null,
            description: null,
          },
          {
            id: 2,
            title: "Бензин",
            code: "benzin",
            my_path: "Нефтепродукты-->Бензин",
            parent: 1,
            description: null,
          },
          {
            id: 14,
            title: "АИ-95",
            code: "ai-95",
            my_path: "Нефтепродукты-->Бензин-->АИ-95",
            parent: 2,
            description: "",
          },
          {
            id: 24,
            title: "АИ-98",
            code: "ai-98",
            my_path: "Нефтепродукты-->Бензин-->АИ-98",
            parent: 2,
            description: null,
          },
          {
            id: 34,
            title: "аи-100",
            code: "ai-100",
            my_path: "Нефтепродукты-->Бензин-->аи-100",
            parent: 2,
            description: "",
          },
          {
            id: 46,
            title: "аи-80",
            code: "ai-80",
            my_path: "Нефтепродукты-->Бензин-->аи-80",
            parent: 2,
            description: null,
          },
          {
            id: 56,
            title: "другое (указать продукт в описании к заказу)",
            code: "drugoe-ukazat-produkt-v-opisanii-k-zakazu",
            my_path: "Нефтепродукты-->Бензин-->другое (указать продукт в описании к заказу)",
            parent: 2,
            description: "",
          },
          {
            id: 57,
            title: "аи-92",
            code: "ai-92-2",
            my_path: "Нефтепродукты-->Бензин-->аи-92",
            parent: 2,
            description: null,
          },
          {
            id: 7,
            title: "дизель",
            code: "dizel",
            my_path: "Нефтепродукты-->дизель",
            parent: 1,
            description: null,
          },
          {
            id: 8,
            title: "арктический",
            code: "arkticheskij",
            my_path: "Нефтепродукты-->дизель-->арктический",
            parent: 7,
            description: null,
          },
          {
            id: 48,
            title: "зимний",
            code: "zimnij",
            my_path: "Нефтепродукты-->дизель-->зимний",
            parent: 7,
            description: null,
          },
          {
            id: 51,
            title: "летний",
            code: "letnij",
            my_path: "Нефтепродукты-->дизель-->летний",
            parent: 7,
            description: null,
          },
          {
            id: 59,
            title: "другое (указать продукт в описании к заказу)",
            code: "drugoe-ukazat-produkt-v-opisanii-k-zakazu-3",
            my_path: "Нефтепродукты-->другое (указать продукт в описании к заказу)",
            parent: 1,
            description: null,
          },
        ],
        date_interval: 2,
        method: {
          id: 23,
          title: "Лабораторные методы измерения плотности, относительной плотности и плотности в градусах API",
          registration_number: "Р 50.2.075 – 2010",
          link: "https://docs.cntd.ru/document/1200085618",
        },
        example_unit: { id: 21, title: "килопаскаль", short_title: "кПа" },
      },
      date_created: "2022-07-07T10:11:36.326162+07:00",
      date_updated: "2022-07-08T09:29:40.450841+07:00",
      sub_results: [
        {
          id: 176,
          parent_result: 263,
          sub_analysis: {
            id: 149,
            title: "плотность при 15°c",
            description: "",
            norm: "-",
            unit: { id: 13, title: "градус Цельсия", short_title: "˚C" },
          },
          value: "34",
          date_result: "2022-07-08T09:28:22.757937+07:00",
          date_created: "2022-07-08T09:28:22.757152+07:00",
          variation: "3",
        },
      ],
      executor: {
        id: 95,
        first_name: "Дмитрий",
        last_name: "Коханенко",
        patronymic: "Васильевич",
        email: "koh@ooo31.com",
        phone: "79132136810",
        is_active: true,
        is_fully_confirmed: true,
        role: 10,
        date_joined: "2021-12-20T14:18:33+07:00",
        is_staff: true,
        is_project_manager: false,
        is_blocked: false,
      },
      status: 40,
    },
    {
      id: 262,
      order: 178,
      analysis: {
        id: 36,
        title: "Определение углеводородного состава нефтепродуктов методом капиллярной газовой хроматографии",
        indicator: "Углеводородный состав",
        description: "",
        price: "10000.00",
        capacity: 300,
        sub_analyses: [
          {
            id: 148,
            title: "углеводородный состав",
            description: "",
            norm: "-",
            unit: { id: 17, title: "процент", short_title: "%" },
          },
        ],
        target: 0,
        devices: [
          {
            id: 3,
            title:
              "Комплекс аппаратно-программный для медицинских исследований на базе хроматографа \"Хроматэк-Кристалл 5000.2\", № 560005",
            number: "560005",
            last_service_date: "2021-08-24",
            next_service_date: "2021-08-25",
          },
        ],
        categories: [
          {
            id: 1,
            title: "Нефтепродукты",
            code: "nefteproduktyi",
            my_path: "Нефтепродукты",
            parent: null,
            description: null,
          },
          {
            id: 2,
            title: "Бензин",
            code: "benzin",
            my_path: "Нефтепродукты-->Бензин",
            parent: 1,
            description: null,
          },
          {
            id: 14,
            title: "АИ-95",
            code: "ai-95",
            my_path: "Нефтепродукты-->Бензин-->АИ-95",
            parent: 2,
            description: "",
          },
          {
            id: 24,
            title: "АИ-98",
            code: "ai-98",
            my_path: "Нефтепродукты-->Бензин-->АИ-98",
            parent: 2,
            description: null,
          },
          {
            id: 34,
            title: "аи-100",
            code: "ai-100",
            my_path: "Нефтепродукты-->Бензин-->аи-100",
            parent: 2,
            description: "",
          },
          {
            id: 46,
            title: "аи-80",
            code: "ai-80",
            my_path: "Нефтепродукты-->Бензин-->аи-80",
            parent: 2,
            description: null,
          },
          {
            id: 56,
            title: "другое (указать продукт в описании к заказу)",
            code: "drugoe-ukazat-produkt-v-opisanii-k-zakazu",
            my_path: "Нефтепродукты-->Бензин-->другое (указать продукт в описании к заказу)",
            parent: 2,
            description: "",
          },
          {
            id: 57,
            title: "аи-92",
            code: "ai-92-2",
            my_path: "Нефтепродукты-->Бензин-->аи-92",
            parent: 2,
            description: null,
          },
          {
            id: 7,
            title: "дизель",
            code: "dizel",
            my_path: "Нефтепродукты-->дизель",
            parent: 1,
            description: null,
          },
          {
            id: 8,
            title: "арктический",
            code: "arkticheskij",
            my_path: "Нефтепродукты-->дизель-->арктический",
            parent: 7,
            description: null,
          },
          {
            id: 48,
            title: "зимний",
            code: "zimnij",
            my_path: "Нефтепродукты-->дизель-->зимний",
            parent: 7,
            description: null,
          },
          {
            id: 51,
            title: "летний",
            code: "letnij",
            my_path: "Нефтепродукты-->дизель-->летний",
            parent: 7,
            description: null,
          },
          {
            id: 58,
            title: "другое (указать продукт в описании к заказу)",
            code: "drugoe-ukazat-produkt-v-opisanii-k-zakazu-2",
            my_path: "Нефтепродукты-->дизель-->другое (указать продукт в описании к заказу)",
            parent: 7,
            description: null,
          },
          {
            id: 55,
            title: "тёмные нп и масла",
            code: "tyomnyie-np-i-masla",
            my_path: "Нефтепродукты-->тёмные нп и масла",
            parent: 1,
            description: null,
          },
          {
            id: 59,
            title: "другое (указать продукт в описании к заказу)",
            code: "drugoe-ukazat-produkt-v-opisanii-k-zakazu-3",
            my_path: "Нефтепродукты-->другое (указать продукт в описании к заказу)",
            parent: 1,
            description: null,
          },
        ],
        date_interval: 48,
        method: {
          id: 1,
          title:
            "Определение индивидуального и группового углеводородного состава методом капиллярной газовой хроматографии",
          registration_number: "ГОСТ 32507-2013",
          link: "https://docs.cntd.ru/document/1200108178",
        },
        example_unit: { id: 21, title: "килопаскаль", short_title: "кПа" },
      },
      date_created: "2022-07-07T10:11:36.326102+07:00",
      date_updated: "2022-07-08T09:29:46.056014+07:00",
      sub_results: [
        {
          id: 177,
          parent_result: 262,
          sub_analysis: {
            id: 148,
            title: "углеводородный состав",
            description: "",
            norm: "-",
            unit: { id: 17, title: "процент", short_title: "%" },
          },
          value: "34",
          date_result: "2022-07-08T09:28:30.509569+07:00",
          date_created: "2022-07-08T09:28:30.509113+07:00",
          variation: "3",
        },
      ],
      executor: {
        id: 95,
        first_name: "Дмитрий",
        last_name: "Коханенко",
        patronymic: "Васильевич",
        email: "koh@ooo31.com",
        phone: "79132136810",
        is_active: true,
        is_fully_confirmed: true,
        role: 10,
        date_joined: "2021-12-20T14:18:33+07:00",
        is_staff: true,
        is_project_manager: false,
        is_blocked: false,
      },
      status: 40,
    },
    {
      id: 261,
      order: 178,
      analysis: {
        id: 2,
        title: "Определение детонационной стойкости бензинов моторным методом",
        indicator: "октановое число",
        description: "",
        price: "2800.00",
        capacity: 1,
        sub_analyses: [
          {
            id: 72,
            title: "октановое число",
            description: "не менее",
            norm: "76,0",
            unit: { id: 15, title: "Условная единица", short_title: "ед." },
          },
          {
            id: 108,
            title: "октановое число",
            description: "не менее",
            norm: "83,0",
            unit: { id: 15, title: "Условная единица", short_title: "ед." },
          },
          {
            id: 64,
            title: "октановое число",
            description: "не менее",
            norm: "85,0",
            unit: { id: 15, title: "Условная единица", short_title: "ед." },
          },
          {
            id: 75,
            title: "октановое число",
            description: "не менее",
            norm: "88,0",
            unit: { id: 15, title: "Условная единица", short_title: "ед." },
          },
        ],
        target: 0,
        devices: [
          {
            id: 7,
            title: "Установка УИТ-85",
            number: "789",
            last_service_date: "2021-08-24",
            next_service_date: "2021-08-29",
          },
        ],
        categories: [
          {
            id: 1,
            title: "Нефтепродукты",
            code: "nefteproduktyi",
            my_path: "Нефтепродукты",
            parent: null,
            description: null,
          },
          {
            id: 2,
            title: "Бензин",
            code: "benzin",
            my_path: "Нефтепродукты-->Бензин",
            parent: 1,
            description: null,
          },
          {
            id: 14,
            title: "АИ-95",
            code: "ai-95",
            my_path: "Нефтепродукты-->Бензин-->АИ-95",
            parent: 2,
            description: "",
          },
          {
            id: 24,
            title: "АИ-98",
            code: "ai-98",
            my_path: "Нефтепродукты-->Бензин-->АИ-98",
            parent: 2,
            description: null,
          },
          {
            id: 34,
            title: "аи-100",
            code: "ai-100",
            my_path: "Нефтепродукты-->Бензин-->аи-100",
            parent: 2,
            description: "",
          },
          {
            id: 46,
            title: "аи-80",
            code: "ai-80",
            my_path: "Нефтепродукты-->Бензин-->аи-80",
            parent: 2,
            description: null,
          },
          {
            id: 56,
            title: "другое (указать продукт в описании к заказу)",
            code: "drugoe-ukazat-produkt-v-opisanii-k-zakazu",
            my_path: "Нефтепродукты-->Бензин-->другое (указать продукт в описании к заказу)",
            parent: 2,
            description: "",
          },
          {
            id: 57,
            title: "аи-92",
            code: "ai-92-2",
            my_path: "Нефтепродукты-->Бензин-->аи-92",
            parent: 2,
            description: null,
          },
        ],
        date_interval: 12,
        method: {
          id: 13,
          title: "Моторный метод определения октанового числа",
          registration_number: "ГОСТ 511",
          link: "https://docs.cntd.ru/document/1200128310",
        },
        example_unit: { id: 21, title: "килопаскаль", short_title: "кПа" },
      },
      date_created: "2022-07-07T10:11:36.326018+07:00",
      date_updated: "2022-07-08T09:29:50.792234+07:00",
      sub_results: [
        {
          id: 181,
          parent_result: 261,
          sub_analysis: {
            id: 75,
            title: "октановое число",
            description: "не менее",
            norm: "88,0",
            unit: { id: 15, title: "Условная единица", short_title: "ед." },
          },
          value: "34",
          date_result: "2022-07-08T09:28:43.811816+07:00",
          date_created: "2022-07-08T09:28:43.811367+07:00",
          variation: "3",
        },
        {
          id: 180,
          parent_result: 261,
          sub_analysis: {
            id: 72,
            title: "октановое число",
            description: "не менее",
            norm: "76,0",
            unit: { id: 15, title: "Условная единица", short_title: "ед." },
          },
          value: "34",
          date_result: "2022-07-08T09:28:43.729202+07:00",
          date_created: "2022-07-08T09:28:43.728734+07:00",
          variation: "3",
        },
        {
          id: 179,
          parent_result: 261,
          sub_analysis: {
            id: 64,
            title: "октановое число",
            description: "не менее",
            norm: "85,0",
            unit: { id: 15, title: "Условная единица", short_title: "ед." },
          },
          value: "34",
          date_result: "2022-07-08T09:28:43.734135+07:00",
          date_created: "2022-07-08T09:28:43.733622+07:00",
          variation: "3",
        },
        {
          id: 178,
          parent_result: 261,
          sub_analysis: {
            id: 108,
            title: "октановое число",
            description: "не менее",
            norm: "83,0",
            unit: { id: 15, title: "Условная единица", short_title: "ед." },
          },
          value: "34",
          date_result: "2022-07-08T09:28:43.726652+07:00",
          date_created: "2022-07-08T09:28:43.726145+07:00",
          variation: "3",
        },
      ],
      executor: {
        id: 95,
        first_name: "Дмитрий",
        last_name: "Коханенко",
        patronymic: "Васильевич",
        email: "koh@ooo31.com",
        phone: "79132136810",
        is_active: true,
        is_fully_confirmed: true,
        role: 10,
        date_joined: "2021-12-20T14:18:33+07:00",
        is_staff: true,
        is_project_manager: false,
        is_blocked: false,
      },
      status: 40,
    },
  ],
  bill: {
    id: 140,
    amount: "18950.00",
    date_created: "2022-07-07T10:11:38.244558+07:00",
    bill_document: "https://predlab.s3.amazonaws.com/media/private/company/21/bill/bill070720221011.pdf",
    status: 80,
    date_closed: "2022-07-11T14:49:58.937199+07:00",
    providing_act:
      "https://predlab.s3.amazonaws.com/media/private/company/21/bill/providing_acts/providing-act11-07-2022T14-49.pdf",
    transfer_document:
      "https://predlab.s3.amazonaws.com/media/private/company/21/bill/ypds/transfer_document11-07-2022T14-49.pdf",
  },
  chat: null,
  date_sample_receiving: "2022-07-07T15:58:13+07:00",
  condition: "температура 23,5°С, влажность 49,1%, атмосферное давление 101,9 кПа",
  date_start_testing: "2022-07-07T17:47:36.325677+07:00",
  date_finish_testing: "2022-07-08T09:33:38.082041+07:00",
  test_report: "https://predlab.s3.amazonaws.com/media/private/order/178/test-report.pdf",
  test_report_ecp:
    // eslint-disable-next-line max-len
    "https://predlab.s3.amazonaws.com/media/private/order/178/%D0%BE%D0%B1%D1%80%D0%B0%D0%B7%D0%B5%D1%86_%D0%B0%D0%BA%D1%82%D0%B0_%D0%BE%D1%82%D0%B1%D0%BE%D1%80%D0%B0_%D0%BF%D1%80%D0%BE%D0%B1.pdf",
};

export const orders = (req, res) => {
  const new_orders_list = { ...orders_list };
  /*

    let newOrdersArray
    newOrdersArray = orders_list.results.filter((order) => {
      if (order.is_paid.toString() === req.query.is_paid.toString() || req.query.is_paid.toString() === '') {
        return order
      }

    })
     newOrdersArray = orders_list.results.filter((order) => {

      if (order.status.toString() === req.query.status.toString() || req.query.status.toString() === '') {
        console.log('iffffff')
        return order
      }
    })
    new_orders_list.results = [...newOrdersArray]
  */

  res.status(200).json({
    ...new_orders_list,
  });
};

export const order = (req, res) => {
  if (req.body.target) {
    orderData.target = req.body.target;
  }
  res.status(200).json(orderData);
};

export const create_order = (req, res) => {
  res.status(200).json({
    id: 5,
    sticker: "sticker",
  });
};

export const add_protocol = (req, res) => {
  orderData.test_report_ecp = "https://predlab.s3.amazonaws.com/media/private/order/178/test-report.pdf";
  res.status(200).json({
    id: 5,
    sticker: "sticker",
  });
};
